const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Sprite,
		C3.Plugins.Shape3D,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.RemoveLayer,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Exps.roundtodp,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetOpacity
	];
};
self.C3_JsPropNameTable = [
	{textyear: 0},
	{textmoney: 0},
	{textozone: 0},
	{textCFC: 0},
	{Kampány: 0},
	{buttoncampaine: 0},
	{status: 0},
	{restart_gomb: 0},
	{close_gomb: 0},
	{text_bevezeto: 0},
	{Szöveg: 0},
	{text_bevezeto2: 0},
	{Szöveg2: 0},
	{button_fridge: 0},
	{Button_dezodor: 0},
	{button_klima: 0},
	{Alakzat: 0},
	{"3DAlakzat": 0},
	{Alakzat2: 0},
	{Alakzat3: 0},
	{Alakzat5: 0},
	{Alakzat4: 0},
	{Alakzat6: 0},
	{Alakzat7: 0},
	{year: 0},
	{money: 0},
	{ozone: 0},
	{CFC: 0},
	{kezdeti_cfc: 0},
	{delta: 0},
	{ozone_alap: 0}
];

self.InstanceType = {
	textyear: class extends self.ITextInstance {},
	textmoney: class extends self.ITextInstance {},
	textozone: class extends self.ITextInstance {},
	textCFC: class extends self.ITextInstance {},
	Kampány: class extends self.IButtonInstance {},
	buttoncampaine: class extends self.IButtonInstance {},
	status: class extends self.ITextInstance {},
	restart_gomb: class extends self.IButtonInstance {},
	close_gomb: class extends self.IButtonInstance {},
	text_bevezeto: class extends self.ITextInstance {},
	Szöveg: class extends self.ITextInstance {},
	text_bevezeto2: class extends self.ITextInstance {},
	Szöveg2: class extends self.ITextInstance {},
	button_fridge: class extends self.IButtonInstance {},
	Button_dezodor: class extends self.IButtonInstance {},
	button_klima: class extends self.IButtonInstance {},
	Alakzat: class extends self.ISpriteInstance {},
	_3DAlakzat: class extends self.I3DShapeInstance {},
	Alakzat2: class extends self.ISpriteInstance {},
	Alakzat3: class extends self.ISpriteInstance {},
	Alakzat5: class extends self.ISpriteInstance {},
	Alakzat4: class extends self.ISpriteInstance {},
	Alakzat6: class extends self.ISpriteInstance {},
	Alakzat7: class extends self.ISpriteInstance {}
}